---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: colorapi
  labels:
    app: colorapi
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: colorapi
  template:
    metadata:
      labels:
        app: colorapi
    spec:
      containers:
        - name: colorapi
          image: particule/simplecolorapi:2.0
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 5000
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: "30s"
        - setWeight: 50
        - pause:
            duration: "30s"
---
apiVersion: v1
kind: Service
metadata:
  name: colorapi
spec:
  ports:
    - port: 80
  selector:
    app: colorapi
  type: LoadBalancer
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  args:
    - name: host
  metrics:
    - name: webcheck
      failureLimit: 1
      interval: 5
      successCondition: result == "ok"
      provider:
        web:
          # paceholders are resolved when an AnalysisRun is created
          url: "http://{{args.host}}/"
          jsonPath: "{$.status}"
